instrumentation:
  root: src
  include-all-sources: true
  verbose: true
  excludes:
    - index.js
    - graphical/__tests__/*.js
    - i18n/__tests__/*.js
    - input/__tests__/*.js
    - misc/__tests__/*.js
reporting:
  dir: "coverage"
